const Homeproduct = [
  {
    id: 1,
    Name: "product1",
    price: "21",
    img: "img/p1.webp",
    cat: "",
    type: "new",
  },
  {
    id: 2,
    Name: "product2",
    price: "22",
    img: "img/p2.webp",
    cat: "",
    type: "new",
  },
  {
    id: 3,
    Name: "product3",
    price: "23",
    img: "img/p3.webp",
    cat: "",
    type: "new",
  },
  {
    id: 4,
    Name: "product4",
    price: "24",
    img: "img/p4.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 5,
    Name: "product5",
    price: "25",
    img: "img/p5.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 6,
    Name: "product6",
    price: "26",
    img: "img/p6.webp",
    cat: "",
    type: "top",
  },
  {
    id: 7,
    Name: "product7",
    price: "27",
    img: "img/p7.webp",
    cat: "",
    type: "top",
  },
  {
    id: 8,
    Name: "product8",
    price: "8",
    img: "img/p8.webp",
    cat: "",
    type: "top",
  },
];

export default Homeproduct;
