const Homeproduct = [
  {
    id: 1,
    Name: "product1",
    price: "21",
    image: "image/p1.webp",
    cat: "",
    type: "new",
  },
  {
    id: 2,
    Name: "product2",
    price: "22",
    image: "image/p2.webp",
    cat: "",
    type: "new",
  },
  {
    id: 3,
    Name: "product3",
    price: "23",
    image: "image/p3.webp",
    cat: "",
    type: "new",
  },
  {
    id: 4,
    Name: "product4",
    price: "24",
    image: "image/p4.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 5,
    Name: "product5",
    price: "25",
    image: "image/p5.webp",
    cat: "",
    type: "featured",
  },
  {
    id: 6,
    Name: "product6",
    price: "26",
    image: "image/p6.webp",
    cat: "",
    type: "top",
  },
  {
    id: 7,
    Name: "product7",
    price: "27",
    image: "image/p7.webp",
    cat: "",
    type: "top",
  },
  {
    id: 8,
    Name: "product8",
    price: "28",
    image: "image/p8.webp",
    cat: "",
    type: "top",
  },
  {
    id: 9,
    Name: "product9",
    price: "29",
    image: "image/p9.webp",
    cat: "",
    type: "top",
  },
  {
    id: 10,
    Name: "product10",
    price: "30",
    image: "image/p10.webp",
    cat: "",
    type: "top",
  },
  {
    id: 11,
    Name: "product11",
    price: "31",
    image: "image/p11.webp",
    cat: "",
    type: "top",
  },
  {
    id: 11,
    Name: "product12",
    price: "32",
    image: "image/p12.webp",
    cat: "",
    type: "top",
  },
];

export default Homeproduct;
